declare @date datetime
set @date = getdate()

delete L_City

insert L_City (Value, [Description],Created, Modified) values (N'ابو رواش',N'ابو رواش',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الازهر',N'الازهر',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'التجمع الخامس',N'التجمع الخامس',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'التحرير',N'التحرير',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الرحاب',N'الرحاب',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الزيتون',N'الزيتون',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'السيدة زينب',N'السيدة زينب',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'السيدة نفيسة',N'السيدة نفيسة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'القصر العيني',N'القصر العيني',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'القلعة',N'القلعة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'المعادي',N'المعادي',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'المعادي الجديدة',N'المعادي الجديدة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'المقطم',N'المقطم',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'النزهة الجديدة',N'النزهة الجديدة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الاميرية',N'الاميرية',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'البساتين',N'البساتين',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'بولاق أبو العلا',N'بولاق أبو العلا',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'بولاق الدكرور',N'بولاق الدكرور',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'جاردن سيتي',N'جاردن سيتي',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'حدائق القبة',N'حدائق القبة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الحلمية',N'الحلمية',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'رمسيس',N'رمسيس',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الزمالك',N'الزمالك',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'شبرا',N'شبرا',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'شبرا الخيمة',N'شبرا الخيمة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الشرابية',N'الشرابية',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'الظاهر',N'الظاهر',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'العباسية',N'العباسية',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'عين شمس',N'عين شمس',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'غمرة',N'غمرة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'القطامية',N'القطامية',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'مدينة 15 مايو',N'مدينة 15 مايو',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'مدينة العبور',N'مدينة العبور',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'مدينة نصر',N'مدينة نصر',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'مساكن شيراتون',N'مساكن شيراتون',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'مصر القديمة',N'مصر القديمة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'المطرية',N'المطرية',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'المنيل',N'المنيل',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'هليوبوليس',N'هليوبوليس',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'وسط القاهرة',N'وسط القاهرة',@date,@date)
insert L_City (Value, [Description],Created, Modified) values (N'أخرى',N'أخرى',@date,@date)
