declare @date datetime
set @date = getdate()

delete L_City

insert L_City (Value, [Description],Created, Modified) values ('Abou Rawash','Abou Rawash',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Azhar','Azhar',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Tagomaa Khames','Tagomaa Khames',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('El Tahrir','El Tahrir',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('El Rehab','El Rehab',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Zaytoon','Zaytoon',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Sayeda Zeinab','Sayeda Zeinab',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Sayeda Naffisa','Sayeda Naffisa',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Kasr El Eini','Kasr El Eini',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Citadel (El-Kal3a)','Citadel (El-Kal3a)',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Maadi','Maadi',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('New Maadi','New Maadi',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Mokattam','Mokattam',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('New Nozha','New Nozha',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Amiria','Amiria',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Basateen','Basateen',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Boulak Abo el Eila','Boulak Abo el Eila',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Boulak El Dakroor','Boulak El Dakroor',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Garden City','Garden City',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Hadaiq Al-Qubba','Hadaiq Al-Qubba',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Helmeya','Helmeya',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Ramsis','Ramsis',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Zamalek','Zamalek',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Shoubra','Shoubra',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Shoubra El Khema','Shoubra El Khema',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Sharabeya','Sharabeya',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Daher','Daher',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Abbasiyya','Abbasiyya',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Ain Shams','Ain Shams',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Ghamra','Ghamra',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Kattamia','Kattamia',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('15th of May City','15th of May City',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Obour City','Obour City',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Nasr City','Nasr City',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Masaken Sheraton','Masaken Sheraton',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Misr El-Kadima','Misr El-Kadima',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Matareya','Matareya',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Manyal','Manyal',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Heliopolis','Heliopolis',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Down Town','Down Town',@date,@date)
insert L_City (Value, [Description],Created, Modified) values ('Others','Others',@date,@date)
